import { ReactNode } from 'react';
import MainNavigation from './layout/MainNavigation';
import MainFooter from './layout/MainFooter';
import Head from 'next/head';

type LayoutProps = {
  children: ReactNode;
};

export default ({ children }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>UwU Pizza~</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>

      <div className='flex flex-col min-h-screen'>
        <MainNavigation />

        {children}
      </div>

      <MainFooter />
    </>
  );
};
